######################################################################
# Automatically generated by qmake (3.1) Tue Mar 12 21:44:35 2024
######################################################################

TEMPLATE = app
TARGET = qmake
INCLUDEPATH += .

# Input
SOURCES += qmake.cpp

QT += widgets gui
